version: "3.9"
services:
  app:
    build: .
    container_name: go-task-runner
    ports:
      - "8000:8000"

  tests:
    image: python:3.11
    container_name: go-task-runner-tests
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - app
    command: >
      bash -c "pip install -r requirements.txt && pytest -v tests.py"
